local FList = require "FList"
describe("FList simple tests", function()
  it("should map", function()
    local list = FList({ 1, 2, 3 })
    assert.are.same({ 2, 3, 4 }, list:map(function(e) return e + 1 end))
  end)
  it("should filter", function()
    local list = FList({ 1, 2, 3 })
    assert.are.same({ 1, 3 }, list:filter(function(e) return e ~= 2 end))
  end)
  it("should reduce", function()
    local list = FList({ 1, 2, 3 })
    assert.are.same(6, list:reduce(function(acc, e) return acc + e end, 0))
  end)
  it("should return size", function()
    local list = FList({ 1, 2, 3 })
    assert.are.same(3, list:size())
  end)
end)

describe("FList advanced tests", function()
  it("should filter then map", function()
    local list = FList({ 1, 2, 3, 4 })
    assert.are.same({ 2, 4, 5 }, list
      :filter(function(e) return e ~= 2 end)
      :map(function(e) return e + 1 end))
  end)
end)
