local Heap = require("utils.PriorityHeap")

describe("Heap", function()
  it("should be able to push to heap and retain min priority", function()
    local h = Heap()
    h:push("B")
    h:push("G")
    h:push("J")
    h:push("A")
    assert.are.same("A", h:peek())
  end)
  it("should be able to push and pop and retain min priority", function()
    local h = Heap()
    h:push("C")
    h:push("D")
    h:push("B")
    h:push("A")
    assert.are.same("A", h:pop())
    assert.are.same("B", h:pop())
    assert.are.same("C", h:pop())
    assert.are.same("D", h:pop())
  end)
end)
